### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "five@localhost.com",
    "password": "123"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "asdfg1@akl.com",
    "password": "akl"
}

### Signout
POST http://localhost:3000/auth/signout

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Find a particular user with a given ID
GET http://localhost:3000/auth/3

### Find all users with a given email
GET http://localhost:3000/auth?email=asd@localhost.com

### Delete a user given id
DELETE http://localhost:3000/auth/122

### Update a User
PATCH http://localhost:3000/auth/222
Content-Type: application/json

{
    "email": "patch@email.com"
}
